package com.bi.dds.mapper;

import com.bi.dds.model.DdsDBConf;
import java.util.List;
import java.util.Map;


public interface DdsDBConfMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    int insert(DdsDBConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    int insertSelective(DdsDBConf record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    DdsDBConf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DdsDBConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DdsDBConf record);

	int deleteLogicByPrimaryKey(int parseInt);
	
	List<DdsDBConf> queryDBInfoList(Map<String,String> map);
	
	int countDBInfoList(Map<String,String> map);
	
	List<DdsDBConf> selectAllAvildDBConfs();
}