package com.bi.dds.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


public class DdsExecLog{
	
    private Integer id;
	
    private Integer mailId;
	
    private String mailName;
	
    private Date createTime;
	
    private Date beginTime;
	
    private Date endTime;
	
    private String errmsg;
	
    private Integer flag;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.id
     *
     * @param id the value for dds_exec_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_exec_log.mail_id
     *
     * @return the value of dds_exec_log.mail_id
     *
     * @mbggenerated
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.mail_id
     *
     * @param mailId the value for dds_exec_log.mail_id
     *
     * @mbggenerated
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_exec_log.mail_name
     *
     * @return the value of dds_exec_log.mail_name
     *
     * @mbggenerated
     */
    public String getMailName() {
        return mailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.mail_name
     *
     * @param mailName the value for dds_exec_log.mail_name
     *
     * @mbggenerated
     */
    public void setMailName(String mailName) {
        this.mailName = mailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_exec_log.create_time
     *
     * @return the value of dds_exec_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.create_time
     *
     * @param createTime the value for dds_exec_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_exec_log.begin_time
     *
     * @return the value of dds_exec_log.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.begin_time
     *
     * @param beginTime the value for dds_exec_log.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_exec_log.end_time
     *
     * @return the value of dds_exec_log.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.end_time
     *
     * @param endTime the value for dds_exec_log.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_exec_log.errmsg
     *
     * @return the value of dds_exec_log.errmsg
     *
     * @mbggenerated
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.errmsg
     *
     * @param errmsg the value for dds_exec_log.errmsg
     *
     * @mbggenerated
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_exec_log.flag
     *
     * @return the value of dds_exec_log.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_exec_log.flag
     *
     * @param flag the value for dds_exec_log.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}