package com.bi.dds.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DdsMailConfExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public DdsMailConfExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andRuleIdListIsNull() {
            addCriterion("rule_id_list is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdListIsNotNull() {
            addCriterion("rule_id_list is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdListEqualTo(String value) {
            addCriterion("rule_id_list =", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListNotEqualTo(String value) {
            addCriterion("rule_id_list <>", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListGreaterThan(String value) {
            addCriterion("rule_id_list >", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListGreaterThanOrEqualTo(String value) {
            addCriterion("rule_id_list >=", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListLessThan(String value) {
            addCriterion("rule_id_list <", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListLessThanOrEqualTo(String value) {
            addCriterion("rule_id_list <=", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListLike(String value) {
            addCriterion("rule_id_list like", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListNotLike(String value) {
            addCriterion("rule_id_list not like", value, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListIn(List<String> values) {
            addCriterion("rule_id_list in", values, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListNotIn(List<String> values) {
            addCriterion("rule_id_list not in", values, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListBetween(String value1, String value2) {
            addCriterion("rule_id_list between", value1, value2, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andRuleIdListNotBetween(String value1, String value2) {
            addCriterion("rule_id_list not between", value1, value2, "ruleIdList");
            return (Criteria) this;
        }

        public Criteria andIsAvildIsNull() {
            addCriterion("is_avild is null");
            return (Criteria) this;
        }

        public Criteria andIsAvildIsNotNull() {
            addCriterion("is_avild is not null");
            return (Criteria) this;
        }

        public Criteria andIsAvildEqualTo(Integer value) {
            addCriterion("is_avild =", value, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildNotEqualTo(Integer value) {
            addCriterion("is_avild <>", value, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildGreaterThan(Integer value) {
            addCriterion("is_avild >", value, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_avild >=", value, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildLessThan(Integer value) {
            addCriterion("is_avild <", value, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildLessThanOrEqualTo(Integer value) {
            addCriterion("is_avild <=", value, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildIn(List<Integer> values) {
            addCriterion("is_avild in", values, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildNotIn(List<Integer> values) {
            addCriterion("is_avild not in", values, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildBetween(Integer value1, Integer value2) {
            addCriterion("is_avild between", value1, value2, "isAvild");
            return (Criteria) this;
        }

        public Criteria andIsAvildNotBetween(Integer value1, Integer value2) {
            addCriterion("is_avild not between", value1, value2, "isAvild");
            return (Criteria) this;
        }

        public Criteria andCrontabIsNull() {
            addCriterion("crontab is null");
            return (Criteria) this;
        }

        public Criteria andCrontabIsNotNull() {
            addCriterion("crontab is not null");
            return (Criteria) this;
        }

        public Criteria andCrontabEqualTo(String value) {
            addCriterion("crontab =", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabNotEqualTo(String value) {
            addCriterion("crontab <>", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabGreaterThan(String value) {
            addCriterion("crontab >", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabGreaterThanOrEqualTo(String value) {
            addCriterion("crontab >=", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabLessThan(String value) {
            addCriterion("crontab <", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabLessThanOrEqualTo(String value) {
            addCriterion("crontab <=", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabLike(String value) {
            addCriterion("crontab like", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabNotLike(String value) {
            addCriterion("crontab not like", value, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabIn(List<String> values) {
            addCriterion("crontab in", values, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabNotIn(List<String> values) {
            addCriterion("crontab not in", values, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabBetween(String value1, String value2) {
            addCriterion("crontab between", value1, value2, "crontab");
            return (Criteria) this;
        }

        public Criteria andCrontabNotBetween(String value1, String value2) {
            addCriterion("crontab not between", value1, value2, "crontab");
            return (Criteria) this;
        }

        public Criteria andSendMailIsNull() {
            addCriterion("send_mail is null");
            return (Criteria) this;
        }

        public Criteria andSendMailIsNotNull() {
            addCriterion("send_mail is not null");
            return (Criteria) this;
        }

        public Criteria andSendMailEqualTo(String value) {
            addCriterion("send_mail =", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotEqualTo(String value) {
            addCriterion("send_mail <>", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailGreaterThan(String value) {
            addCriterion("send_mail >", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailGreaterThanOrEqualTo(String value) {
            addCriterion("send_mail >=", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailLessThan(String value) {
            addCriterion("send_mail <", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailLessThanOrEqualTo(String value) {
            addCriterion("send_mail <=", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailLike(String value) {
            addCriterion("send_mail like", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotLike(String value) {
            addCriterion("send_mail not like", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailIn(List<String> values) {
            addCriterion("send_mail in", values, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotIn(List<String> values) {
            addCriterion("send_mail not in", values, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailBetween(String value1, String value2) {
            addCriterion("send_mail between", value1, value2, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotBetween(String value1, String value2) {
            addCriterion("send_mail not between", value1, value2, "sendMail");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIsSendMsIsNull() {
            addCriterion("is_send_ms is null");
            return (Criteria) this;
        }

        public Criteria andIsSendMsIsNotNull() {
            addCriterion("is_send_ms is not null");
            return (Criteria) this;
        }

        public Criteria andIsSendMsEqualTo(Integer value) {
            addCriterion("is_send_ms =", value, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsNotEqualTo(Integer value) {
            addCriterion("is_send_ms <>", value, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsGreaterThan(Integer value) {
            addCriterion("is_send_ms >", value, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_send_ms >=", value, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsLessThan(Integer value) {
            addCriterion("is_send_ms <", value, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsLessThanOrEqualTo(Integer value) {
            addCriterion("is_send_ms <=", value, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsIn(List<Integer> values) {
            addCriterion("is_send_ms in", values, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsNotIn(List<Integer> values) {
            addCriterion("is_send_ms not in", values, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsBetween(Integer value1, Integer value2) {
            addCriterion("is_send_ms between", value1, value2, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andIsSendMsNotBetween(Integer value1, Integer value2) {
            addCriterion("is_send_ms not between", value1, value2, "isSendMs");
            return (Criteria) this;
        }

        public Criteria andMobileNumIsNull() {
            addCriterion("mobile_num is null");
            return (Criteria) this;
        }

        public Criteria andMobileNumIsNotNull() {
            addCriterion("mobile_num is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNumEqualTo(String value) {
            addCriterion("mobile_num =", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumNotEqualTo(String value) {
            addCriterion("mobile_num <>", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumGreaterThan(String value) {
            addCriterion("mobile_num >", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_num >=", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumLessThan(String value) {
            addCriterion("mobile_num <", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumLessThanOrEqualTo(String value) {
            addCriterion("mobile_num <=", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumLike(String value) {
            addCriterion("mobile_num like", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumNotLike(String value) {
            addCriterion("mobile_num not like", value, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumIn(List<String> values) {
            addCriterion("mobile_num in", values, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumNotIn(List<String> values) {
            addCriterion("mobile_num not in", values, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumBetween(String value1, String value2) {
            addCriterion("mobile_num between", value1, value2, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMobileNumNotBetween(String value1, String value2) {
            addCriterion("mobile_num not between", value1, value2, "mobileNum");
            return (Criteria) this;
        }

        public Criteria andMsContentIsNull() {
            addCriterion("ms_content is null");
            return (Criteria) this;
        }

        public Criteria andMsContentIsNotNull() {
            addCriterion("ms_content is not null");
            return (Criteria) this;
        }

        public Criteria andMsContentEqualTo(String value) {
            addCriterion("ms_content =", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentNotEqualTo(String value) {
            addCriterion("ms_content <>", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentGreaterThan(String value) {
            addCriterion("ms_content >", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentGreaterThanOrEqualTo(String value) {
            addCriterion("ms_content >=", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentLessThan(String value) {
            addCriterion("ms_content <", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentLessThanOrEqualTo(String value) {
            addCriterion("ms_content <=", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentLike(String value) {
            addCriterion("ms_content like", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentNotLike(String value) {
            addCriterion("ms_content not like", value, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentIn(List<String> values) {
            addCriterion("ms_content in", values, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentNotIn(List<String> values) {
            addCriterion("ms_content not in", values, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentBetween(String value1, String value2) {
            addCriterion("ms_content between", value1, value2, "msContent");
            return (Criteria) this;
        }

        public Criteria andMsContentNotBetween(String value1, String value2) {
            addCriterion("ms_content not between", value1, value2, "msContent");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyIsNull() {
            addCriterion("is_send_empty is null");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyIsNotNull() {
            addCriterion("is_send_empty is not null");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyEqualTo(Integer value) {
            addCriterion("is_send_empty =", value, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyNotEqualTo(Integer value) {
            addCriterion("is_send_empty <>", value, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyGreaterThan(Integer value) {
            addCriterion("is_send_empty >", value, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_send_empty >=", value, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyLessThan(Integer value) {
            addCriterion("is_send_empty <", value, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyLessThanOrEqualTo(Integer value) {
            addCriterion("is_send_empty <=", value, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyIn(List<Integer> values) {
            addCriterion("is_send_empty in", values, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyNotIn(List<Integer> values) {
            addCriterion("is_send_empty not in", values, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyBetween(Integer value1, Integer value2) {
            addCriterion("is_send_empty between", value1, value2, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andIsSendEmptyNotBetween(Integer value1, Integer value2) {
            addCriterion("is_send_empty not between", value1, value2, "isSendEmpty");
            return (Criteria) this;
        }

        public Criteria andRuleTableIsNull() {
            addCriterion("rule_table is null");
            return (Criteria) this;
        }

        public Criteria andRuleTableIsNotNull() {
            addCriterion("rule_table is not null");
            return (Criteria) this;
        }

        public Criteria andRuleTableEqualTo(String value) {
            addCriterion("rule_table =", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableNotEqualTo(String value) {
            addCriterion("rule_table <>", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableGreaterThan(String value) {
            addCriterion("rule_table >", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableGreaterThanOrEqualTo(String value) {
            addCriterion("rule_table >=", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableLessThan(String value) {
            addCriterion("rule_table <", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableLessThanOrEqualTo(String value) {
            addCriterion("rule_table <=", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableLike(String value) {
            addCriterion("rule_table like", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableNotLike(String value) {
            addCriterion("rule_table not like", value, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableIn(List<String> values) {
            addCriterion("rule_table in", values, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableNotIn(List<String> values) {
            addCriterion("rule_table not in", values, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableBetween(String value1, String value2) {
            addCriterion("rule_table between", value1, value2, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andRuleTableNotBetween(String value1, String value2) {
            addCriterion("rule_table not between", value1, value2, "ruleTable");
            return (Criteria) this;
        }

        public Criteria andIsDependentIsNull() {
            addCriterion("is_dependent is null");
            return (Criteria) this;
        }

        public Criteria andIsDependentIsNotNull() {
            addCriterion("is_dependent is not null");
            return (Criteria) this;
        }

        public Criteria andIsDependentEqualTo(Integer value) {
            addCriterion("is_dependent =", value, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentNotEqualTo(Integer value) {
            addCriterion("is_dependent <>", value, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentGreaterThan(Integer value) {
            addCriterion("is_dependent >", value, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_dependent >=", value, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentLessThan(Integer value) {
            addCriterion("is_dependent <", value, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentLessThanOrEqualTo(Integer value) {
            addCriterion("is_dependent <=", value, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentIn(List<Integer> values) {
            addCriterion("is_dependent in", values, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentNotIn(List<Integer> values) {
            addCriterion("is_dependent not in", values, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentBetween(Integer value1, Integer value2) {
            addCriterion("is_dependent between", value1, value2, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDependentNotBetween(Integer value1, Integer value2) {
            addCriterion("is_dependent not between", value1, value2, "isDependent");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dds_mail_conf
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dds_mail_conf
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}