package com.bi.dds.model;

import java.util.Date;

public class DdsMailConf{
	
    private Integer id;
	
    private String subject;
	
    private String ruleIdList;
	
    private Integer isAvild;
	
    private String crontab;
	
    private String sendMail;
	
    private Date createTime;
	
    private Integer isSendMs;
	
    private String mobileNum;
	
    private String msContent;
	
    private Integer isSendEmpty;
	
    private String ruleTable;
	
    private Integer isDependent;
	
    private Integer isDeleted;
    
    private String sqlParam;
    
    private String excelPath;

    private String ruleZeusTable;
    
    public String getExcelPath() {
		return excelPath;
	}
	public void setExcelPath(String excelPath) {
		this.excelPath = excelPath;
	}
	public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.subject
     *
     * @return the value of dds_mail_conf.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.subject
     *
     * @param subject the value for dds_mail_conf.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.rule_id_list
     *
     * @return the value of dds_mail_conf.rule_id_list
     *
     * @mbggenerated
     */
    public String getRuleIdList() {
        return ruleIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.rule_id_list
     *
     * @param ruleIdList the value for dds_mail_conf.rule_id_list
     *
     * @mbggenerated
     */
    public void setRuleIdList(String ruleIdList) {
        this.ruleIdList = ruleIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.is_avild
     *
     * @return the value of dds_mail_conf.is_avild
     *
     * @mbggenerated
     */
    public Integer getIsAvild() {
        return isAvild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.is_avild
     *
     * @param isAvild the value for dds_mail_conf.is_avild
     *
     * @mbggenerated
     */
    public void setIsAvild(Integer isAvild) {
        this.isAvild = isAvild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.crontab
     *
     * @return the value of dds_mail_conf.crontab
     *
     * @mbggenerated
     */
    public String getCrontab() {
        return crontab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.crontab
     *
     * @param crontab the value for dds_mail_conf.crontab
     *
     * @mbggenerated
     */
    public void setCrontab(String crontab) {
        this.crontab = crontab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.send_mail
     *
     * @return the value of dds_mail_conf.send_mail
     *
     * @mbggenerated
     */
    public String getSendMail() {
        return sendMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.send_mail
     *
     * @param sendMail the value for dds_mail_conf.send_mail
     *
     * @mbggenerated
     */
    public void setSendMail(String sendMail) {
        this.sendMail = sendMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.create_time
     *
     * @return the value of dds_mail_conf.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.create_time
     *
     * @param createTime the value for dds_mail_conf.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.is_send_ms
     *
     * @return the value of dds_mail_conf.is_send_ms
     *
     * @mbggenerated
     */
    public Integer getIsSendMs() {
        return isSendMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.is_send_ms
     *
     * @param isSendMs the value for dds_mail_conf.is_send_ms
     *
     * @mbggenerated
     */
    public void setIsSendMs(Integer isSendMs) {
        this.isSendMs = isSendMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.mobile_num
     *
     * @return the value of dds_mail_conf.mobile_num
     *
     * @mbggenerated
     */
    public String getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.mobile_num
     *
     * @param mobileNum the value for dds_mail_conf.mobile_num
     *
     * @mbggenerated
     */
    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.ms_content
     *
     * @return the value of dds_mail_conf.ms_content
     *
     * @mbggenerated
     */
    public String getMsContent() {
        return msContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.ms_content
     *
     * @param msContent the value for dds_mail_conf.ms_content
     *
     * @mbggenerated
     */
    public void setMsContent(String msContent) {
        this.msContent = msContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.is_send_empty
     *
     * @return the value of dds_mail_conf.is_send_empty
     *
     * @mbggenerated
     */
    public Integer getIsSendEmpty() {
        return isSendEmpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.is_send_empty
     *
     * @param isSendEmpty the value for dds_mail_conf.is_send_empty
     *
     * @mbggenerated
     */
    public void setIsSendEmpty(Integer isSendEmpty) {
        this.isSendEmpty = isSendEmpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.rule_table
     *
     * @return the value of dds_mail_conf.rule_table
     *
     * @mbggenerated
     */
    public String getRuleTable() {
        return ruleTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.rule_table
     *
     * @param ruleTable the value for dds_mail_conf.rule_table
     *
     * @mbggenerated
     */
    public void setRuleTable(String ruleTable) {
        this.ruleTable = ruleTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.is_dependent
     *
     * @return the value of dds_mail_conf.is_dependent
     *
     * @mbggenerated
     */
    public Integer getIsDependent() {
        return isDependent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.is_dependent
     *
     * @param isDependent the value for dds_mail_conf.is_dependent
     *
     * @mbggenerated
     */
    public void setIsDependent(Integer isDependent) {
        this.isDependent = isDependent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dds_mail_conf.is_deleted
     *
     * @return the value of dds_mail_conf.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dds_mail_conf.is_deleted
     *
     * @param isDeleted the value for dds_mail_conf.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
	public String getSqlParam() {
		return sqlParam;
	}
	public void setSqlParam(String sqlParam) {
		this.sqlParam = sqlParam;
	}

    public String getRuleZeusTable() {
        return ruleZeusTable;
    }

    public void setRuleZeusTable(String ruleZeusTable) {
        this.ruleZeusTable = ruleZeusTable;
    }
}